### ISSUE TITLE
Drop IE11 Support

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-scroll-modifiers#183]
Once we're very far from needing IE11 support, cut a breaking release that drops IE11 support by no longer checking to see if IntersectionObserver exists and just assuming it's there in every browser.

**Comment by chriskrycho** [comment]
We may want a small label/project/milestone to track other things which can go in that breaking change, including dropping the ember-decorators-polyfill.

**Comment by elwayman02** [comment]
Technically, those are separate issues, but I do want to file a ticket for that.
