### ISSUE TITLE
Indeterministic race condition between `onEnter` trigger and `click` on load more button

### ISSUE THREAD

**Issue by alankyshum** [elwayman02/ember-scroll-modifiers#300]
Hi Team,

# Context

We have used `{{did-intersect}}` modifier in a load more button, and it triggers `this.loadMore` on `onEnter` and `click`.

```hbs
<Container>
  <LoadMoreButton {{did-intersect onEnter=this.loadMore}} {{on "click" this.loadMore}} />
  <MessageList />
</Container>
```

# Issue

When the component was tested, the `<LoadMoreButton />` was initially outside the viewport of the `<Container />`. But when we run

```js
await click(LoadMoreButton);
```

the `<LoadMoreButton />` was scrolled into view, triggering `onEnter=this.loadMore` and `{{on "click" this.loadMore}}`.

## Problem

In some cases (usually in CLI mode), `this.loadMore.callCount === 2`, sometimes it's `this.loadMore.callCount === 1`.

## Current Workaround

1. We can pass 2 different methods that do `loadMore` but that's mixing tests into app code, which is not ideal because that was needed only to pass a test.
```hbs
  <LoadMoreButton {{did-intersect onEnter=this.loadMoreOnScroll}} {{on "click" this.loadMoreOnClick}} />
```
2. We have tried the following, but the click action seems to have called loadMore twice.

```js
await click(LoadMoreButton);
this.loadMore.resetHistory(); // if the click action pulls the <LoadMoreButton /> into view, we reset the callCount

await click(LoadMoreButton);
assert.equal(this.loadMore.callCount, 1);
```

# Asks

I have read the integration tests for `ember-scroll-modifier` but the services were stub, so I couldn't find a case like this. Could you advise on how we want to make sure the following test result?

```js
assert.equal(this.loadMore.callCount, 2, 'it triggers loadMore on onEnter and click');
```

**Comment by elwayman02** [comment]
I would not recommend allowing your tests to actually execute the IntersectionObserver behavior, as that's difficult to predict within the text container. Ideally, you would mock the `did-intersect` modifier class in your test, giving you full control over when the callback executes. All you need to test is the integration point between the modifier and your code, not the internals of the modifier itself (which are tested within this package). This is the same reason we stub services in our own tests, because we don't need to test that the IntersectionObserver manager works, we just need to test that our integration with it is correct. Does that make sense?

**Comment by elwayman02** [comment]
To give a quick and dirty example, your test could do something like this:

```
let onEnter;
class DidIntersectMock { 
  constructor() {
    onEnter = this.args.named.onEnter;
  }
}

...

hooks.beforeEach(function () {
  this.owner.register('modifier:did-intersect', DidIntersectMock);
});

...

//in your test
onEnter();
// assert behavior your code is supposed to exhibit after the callback fires
```

You might have to tweak the exact syntax of this, but the solution should be pretty close to what I've shown above.

**Comment by elwayman02** [comment]
@ygongdev what do you think about the idea of adding a testing section to the docs that basically shows how to do this?

**Comment by ygongdev** [comment]
My personal opinion is that the consumer should not be bothered with all the setup just to test to see if the did-intersect is working properly. We should provide the `addon-test-support` helpers.

All the tests I've seen is people only care that the UI is deterministic after performing an event that triggers the `did-intersect` modifier.
I've seen people stub the `IntersectionObserver` making that deterministic but as mentioned above, that is not ideal either, e.g

```
await scrollToBottom()
await IntersectionObserverMock.forceEnter(); // deterministically trigger the did-intersect onEnter method
```

However, I think we can adapt a similar API format from ^.

We can provide some initial setup like `setupDidIntersectMock`, which registers a mock of `didIntersect` to replace the real modifier and then register the real one back after test is done.

```
import setupDidIntersectMock from 'ember-scroll-modifiers/test-support/did-intersect-mock';

hooks.beforeEach(function() {
  this.didIntersectMock = setupDidIntersectMock(this);
});

await click(LoadMoreButton);
await this.didIntersectMock.onEnter(); // force a deterministic `onEnter` 
this.loadMore.resetHistory(); // if the click action pulls the <LoadMoreButton /> into view, we reset the callCount

await click(LoadMoreButton);
assert.equal(this.loadMore.callCount, 1);
```

**Comment by elwayman02** [comment]
@ygongdev I think that's a great idea. Can you put this design in #243? I think what you've laid out here is a much better idea than what we came up with so far. Nice!

**Comment by alankyshum** [comment]
Thanks for your prompt response. I also like the idea of having a ```
`didIntersectMock`, that way we can make sure the click action has triggered the `loadMore` once and we can move on to the real test.

Or taking it further, we can stub the `onEnter` to make it a dummy function, so to make `this.loadMore.callCount === 1` at all time.

```js
this.didIntersectMock.onEnter = this.sandbox.stub();
await click(LoadMoreButton);
// Whether it triggers onEnter or not, it doesn't matter anymore

assert.equal(this.loadMore.callCount, 1, 'it trigger loadMore on click');
```

**Comment by elwayman02** [comment]
Fun fact: You don't need to do `this.sandbox` anymore, because the Sinon object has been its own sandbox by default for a couple years now. All you need to do is call `Sinon.stub`, and you don't even have to remember to manually clean it up if you are using my package [`ember-sinon-qunit`](https://github.com/elwayman02/ember-sinon-qunit).

**Comment by ygongdev** [comment]
Unfortunately, It seems like `modifier` might not be lookup-able. Investigating to see if this was a bug or intended.

**Comment by ygongdev** [comment]
If ^ doesn't work, I guess we can set up some test-waiters to make the async behavior more deterministic, will not require much change on the consumer side.

**Comment by alankyshum** [comment]
HI Team,

I have currently created an addon to unblock our tests

```js
export default function setupDidIntersectModifier(hooks) {
  hooks.beforeEach(function() {
    const didIntersectModifierMock = {};
    this.didIntersectModifierMock = didIntersectModifierMock;

    this.owner.register(
      'modifier:did-intersect',
      class DidIntersectModifierMock extends Modifier {
        constructor() {
          super(...arguments);
          didIntersectModifierMock.onEnter = this.args.named.onEnter;
        }
      }
    );
  });
}
```

and we consume the helper in the tests

```js
module('Integration | MessageListComponent', function(hooks) {
  setupDidIntersectModifier(hooks);

  test('when clicking the load more button', function(assert) {
    
    
  });

  test('when scrolling down the list of messages', function(assert) {
    await scrollDown(MessageList);

    this.loadMoreStub.resetHistory();
    this.didIntersectModifierMock.onEnter();
    assert.equal(this.loadMoreStub.callCount, 1, 'it calls loadMore when did-intersect[onEnter] is triggered');
  });
});
```

**Comment by ygongdev** [comment]
I think this is a good start, but the one from this library will need to be a lot more robust. We're currently exploring some options.

**Comment by elwayman02** [comment]
Glad to hear that worked to unblock you, and thanks for sharing your approach! We'll hopefully have some designs in place for a long-term shared solution in the future. :)

Feel free to close this issue if you feel it's resolved for now. Otherwise, I'd be happy to help you work through to a resolution!

**Comment by alankyshum** [comment]
The current workaround suits our need and closing the issue for now :)
Thanks all for the great support!

**Comment by ygongdev** [comment]
FYI #305
