### ISSUE TITLE
Move documentation from e-c-addon-docs to field-guide

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-scroll-modifiers#359]
e-c-addon-docs is more or less unmaintained, so let's move our docs to the future and use `field-guide` instead. Here's an example of a similar addon that uses field-guide:

https://github.com/elwayman02/ember-resize-modifier/tree/master/docs

Setup should be fairly simple - Copy the markdown files from e-c-addon-docs to the location [field-guide](https://github.com/empress/field-guide) expects them to be and delete any e-c-addon-docs code from the demo app.

**Comment by garrettwelson** [comment]
Hello! I'm definitely interested in taking this on. I've used the addon a fair amount and love working with it

**Comment by elwayman02** [comment]
One interesting part of this project will be migrating the living demo. Thankfully, the example I linked above shows how field-guide supports creating component classes to back the demo code in the markdown files. You can find that file here: https://github.com/elwayman02/ember-resize-modifier/blob/master/docs/modifiers/did-resize.js

**Comment by elwayman02** [comment]
Fixed!
