### ISSUE TITLE
Fix ember-modifier deprecations

### ISSUE THREAD

**Issue by sebastianhelbig** [elwayman02/ember-scroll-modifiers#718]
The `ember-modifer.*` deprecations should be fixed instead of silenced.

**Comment by fpauser** [comment]
Should be fixed with #723 - now we need a fresh release.

**Comment by elwayman02** [comment]
Thanks for fixing these!

For context, the reason we silence the deprecations isn't to avoid fixing them, but just to keep the build logs clean until we have a chance to do so. :)
