### ISSUE TITLE
Published package contains the entire yarn cache

### ISSUE THREAD

**Issue by irminsul** [elwayman02/ember-scroll-modifiers#919]
The currently published version of this package (https://registry.npmjs.org/ember-scroll-modifiers/-/ember-scroll-modifiers-7.0.0.tgz) contains a `.yarn` directory which bloats the archive size to over 64 MiB.

To fix that, update this repo's `.gitignore` file as per [the yarn docs](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) and publish a new version of the package without the bloat 🙂

**Comment by elwayman02** [comment]
Fixed by #937
